---
28Ga:
    markers:
        gbsl.28Ga: 0
        gbsl.gym28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28Ga/index.mdx
        - section: /einzellektion.json
          material: /90-Structure/klassen/28Ga/einzellektion.json
        - section: /praktikum.json
          material: /90-Structure/klassen/28Ga/praktikum.json
        - section: /termine_fs25.json
          material: /90-Structure/klassen/28Ga/termine_fs25.json
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28Ga/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2024
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics
        - section: 04-Programmieren-1
          material: Programmieren-1
        - section: 05-IN-Biber-2024
          material: IN-Biber/2024
        - section: 06-Information-Daten
          material: Information-Daten
        - section: 07-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 08-Repetition-IN-GYM1/index.mdx
          material: Repetition-2025/Repetition-GYM28-Lang.mdx
        - section: 09-Kryptologie
          material: Kryptologie
        - section: 10-Data-Management
          material: Data-Management-2025
        - section: 11-Netzwerke
          material: Netzwerke-2026
          ignore:
              - 51-Networking-the-Nerds.mdx
              - 60-Repetition.mdx
              - 70-Ausblicke
        - section: 99-Probe-DM/index.mdx
          material: tw-confidential-material/Probe-Data-Management-GYM28/28Ga.mdx
28Gd:
    markers:
        gbsl.28Gd: 0
        gbsl.gym28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28Gd/index.mdx
        - section: /einzellektion.json
          material: /90-Structure/klassen/28Gd/einzellektion.json
        - section: /praktikum.json
          material: /90-Structure/klassen/28Gd/praktikum.json
        - section: /termine_fs25.json
          material: /90-Structure/klassen/28Gd/termine_fs25.json
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28Gd/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2024
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics
        - section: 04-Programmieren-1
          material: Programmieren-1
        - section: 05-IN-Biber-2024
          material: IN-Biber/2024
        - section: 06-Information-Daten
          material: Information-Daten
        - section: 07-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 08-Repetition-IN-GYM1/index.mdx
          material: Repetition-2025/Repetition-GYM28-Lang.mdx
        - section: 09-Kryptologie
          material: Kryptologie
        - section: 10-Data-Management
          material: Data-Management-2025
        - section: 11-Netzwerke
          material: Netzwerke-2026
          ignore:
              - 51-Networking-the-Nerds.mdx
              - 60-Repetition.mdx
              - 70-Ausblicke
        - section: 99-Probe-DM/index.mdx
          material: tw-confidential-material/Probe-Data-Management-GYM28/28Gd.mdx
28Gf:
    markers:
        gbsl.28Gf: 0
        gbsl.gym28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28Gf/index.mdx
        - section: /einzellektion.json
          material: /90-Structure/klassen/28Gf/einzellektion.json
        - section: /praktikum.json
          material: /90-Structure/klassen/28Gf/praktikum.json
        - section: /termine_fs25.json
          material: /90-Structure/klassen/28Gf/termine_fs25.json
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28Gf/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2024
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics
        - section: 04-Programmieren-1
          material: Programmieren-1
        - section: 05-IN-Biber-2024
          material: IN-Biber/2024
        - section: 06-Information-Daten
          material: Information-Daten
        - section: 07-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 08-Repetition-IN-GYM1/index.mdx
          material: Repetition-2025/Repetition-GYM28-Kurz.mdx
        - section: 09-Kryptologie
          material: Kryptologie
        - section: 10-Data-Management
          material: Data-Management-2025
        - section: 11-Netzwerke
          material: Netzwerke-2026
          ignore:
              - 51-Networking-the-Nerds.mdx
              - 60-Repetition.mdx
              - 70-Ausblicke
        - section: 99-Probe-DM/index.mdx
          material: tw-confidential-material/Probe-Data-Management-GYM28/28Gf.mdx

28Gh:
    markers:
        gbsl.28Gh: 0
        gbsl.gym28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28Gh/index.mdx
        - section: /einzellektion.json
          material: /90-Structure/klassen/28Gh/einzellektion.json
        - section: /praktikum.json
          material: /90-Structure/klassen/28Gh/praktikum.json
        - section: /termine_fs25.json
          material: /90-Structure/klassen/28Gh/termine_fs25.json
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28Gh/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2024
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics
        - section: 04-Programmieren-1
          material: Programmieren-1
        - section: 05-IN-Biber-2024
          material: IN-Biber/2024
        - section: 06-Information-Daten
          material: Information-Daten
        - section: 07-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 08-Repetition-IN-GYM1/index.mdx
          material: Repetition-2025/Repetition-GYM28-Kurz.mdx
        - section: 09-Kryptologie
          material: Kryptologie
        - section: 10-Data-Management
          material: Data-Management-2025
        - section: 11-Netzwerke
          material: Netzwerke-2026
          ignore:
              - 51-Networking-the-Nerds.mdx
              - 60-Repetition.mdx
              - 70-Ausblicke
        - section: 99-Probe-DM/index.mdx
          material: tw-confidential-material/Probe-Data-Management-GYM28/28Gh.mdx
28mU:
    markers:
        gbsl.28mU: 0
        gbsl.gym28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28mU/index.mdx
        - section: /einzellektion.json
          material: /90-Structure/klassen/28mU/einzellektion.json
        - section: /praktikum.json
          material: /90-Structure/klassen/28mU/praktikum.json
        - section: /termine_fs25.json
          material: /90-Structure/klassen/28mU/termine_fs25.json
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28mU/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2024
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics
        - section: 04-Programmieren-1
          material: Programmieren-1
        - section: 05-IN-Biber-2024
          material: IN-Biber/2024
        - section: 06-Information-Daten
          material: Information-Daten
        - section: 07-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 08-Repetition-IN-GYM1/index.mdx
          material: Repetition-2025/Repetition-GYM28-Kurz.mdx
        - section: 09-Kryptologie
          material: Kryptologie
        - section: 10-Data-Management
          material: Data-Management-2025
        - section: 11-Netzwerke
          material: Netzwerke-2026
          ignore:
              - 51-Networking-the-Nerds.mdx
              - 60-Repetition.mdx
              - 70-Ausblicke
        - section: 99-Probe-DM/index.mdx
          material: tw-confidential-material/Probe-Data-Management-GYM28/28mU.mdx
29Ge:
    markers:
        gbsl.29Ge: 0
        gbsl.gym29: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/29Ge/index.mdx
        - section: /einzellektion.json
          material: /90-Structure/klassen/29Ge/einzellektion.json
        - section: /praktikum.json
          material: /90-Structure/klassen/29Ge/praktikum.json
        - section: 00-MyGBSL
          material: MyGBSL
        - section: 02-Onboarding
          material: Onboarding-2025
        - section: 03-Erste-Hilfe
          material: Erste-Hilfe
        - section: 04-BYOD-Basics
          material: BYOD-Basics-2025
          ignore:
              - 99-Interviews-Repetition.mdx
        - section: 05-Programmieren
          material: Programmieren-2025
          ignore:
              - 04-Advent-of-Code
        - section: 06-IN-Biber-2025
          material: IN-Biber/2025
        - section: 07-SOL-Projekt-GYM1
          material: SOL-Text-Adventure-29Ge
28Fa:
    markers:
        gbsl.28Fa: 0
        gbsl.fms28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28Fa/index.mdx
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28Fa/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2025
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics-2025
          ignore:
              - 01-Probe.mdx
              - 99-Interviews-Repetition.mdx
        - section: 04-Programmieren
          material: Programmieren-2025
          ignore:
              - 04-Advent-of-Code
        - section: 05-IN-Biber-2025
          material: IN-Biber/2025
28Fb:
    markers:
        gbsl.28Fb: 0
        gbsl.fms28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28Fb/index.mdx
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28Fb/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2025
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics-2025
          ignore:
              - 01-Probe.mdx
              - 99-Interviews-Repetition.mdx
        - section: 04-Programmieren
          material: Programmieren-2025
          ignore:
              - 04-Advent-of-Code
              - 99-Interviews-Repetition.mdx
        - section: 05-IN-Biber-2025
          material: IN-Biber/2025
28Fc:
    markers:
        gbsl.28Fc: 0
        gbsl.fms28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/28Fc/index.mdx
        - section: /termine_hs25.json
          material: /90-Structure/klassen/28Fc/termine_hs25.json
        - section: 01-Onboarding
          material: Onboarding-2025
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics-2025
          ignore:
              - 01-Probe.mdx
        - section: 04-Programmieren
          material: Programmieren-2025
          ignore:
              - 04-Advent-of-Code
        - section: 05-IN-Biber-2025
          material: IN-Biber/2025

# === Development === #
draft:
    markers:
        gbsl.draft: 0
        gbsl.gym28: 1
    mappings:
        - section: /index.mdx
          material: /90-Structure/klassen/Draft/index.mdx
        - section: 99-Probe-Data-Management
          material: tw-confidential-material/Probe-Data-Management-GYM28
        - section: 100-Probe-Data-Management-NP1
          material: tw-confidential-material/Probe-Data-Management-GYM28-NP1
